import Link from "next/link";

const pillars=[
 {number:"01",label:"SPEND SMART",question:"Which card should I use right now?",answer:"Rank the cards you already hold for a real purchase—after reward rates, caps, exclusions and verified conditions.",cta:"Rank my wallet",accent:"violet"},
 {number:"02",label:"USE POINTS BETTER",question:"What should I do with the points I already have?",answer:"Compare direct redemption, vouchers and transfer routes by net value, taxes, expiry, limits and risk.",cta:"Find my best use",accent:"cyan"},
 {number:"03",label:"PLAN MY TRIP",question:"What is the smartest route to the trip I actually want?",answer:"Bring cards, points, airline miles and live cash fares together to expose the strongest route and any shortfall.",cta:"Plan with points",accent:"coral"}
];

export default function Home(){return <main className="page homePage">
 <nav className="nav"><Link className="brand" href="/">Point<span>Pilot</span></Link><div className="pricingNavLinks"><Link href="/cards">India 30</Link><Link href="/pricing">Pricing</Link><Link className="linkBtn" href="/login">Sign in</Link></div></nav>
 <section className="hero decisionHero"><div className="eyebrow">REWARDS INTELLIGENCE • BUILT FOR INDIA</div><h1>Every spend.<br/>Every point.<br/><em>One smarter decision.</em></h1><p>PointPilot tells you which card to use, how to extract more value from your points, and the smartest route to the trip you want—with transparent calculations and verified rules.</p><div className="actions"><Link className="btn primary" href="/login">Open my command centre →</Link><a className="btn ghost" href="#decisions">See the three decisions</a></div><div className="heroTrust"><span>Verified issuer rules</span><span>Transparent ₹ / point</span><span>No fake award availability</span></div></section>
 <section className="decisionIntro" id="decisions"><span className="sectionKicker">THE POINTPILOT METHOD</span><h2>Three questions. One connected answer.</h2><p>Start with the purchase in front of you, protect the value already in your wallet, then turn it into a trip worth taking.</p></section>
 <section className="pillarGrid">{pillars.map(pillar=><article className={`pillarCard ${pillar.accent}`} key={pillar.number}><div className="pillarTop"><i>{pillar.number}</i><span>{pillar.label}</span></div><h3>{pillar.question}</h3><p>{pillar.answer}</p><Link href="/login">{pillar.cta} <span>↗</span></Link></article>)}</section>
 <section className="decisionFlow" aria-label="PointPilot decision flow"><div><i>01</i><span>Tell us the purchase or trip</span></div><b>→</b><div><i>02</i><span>Use your real wallet</span></div><b>→</b><div><i>03</i><span>Compare verified routes</span></div><b>→</b><div><i>04</i><span>Act with the full math</span></div></section>
 <div className="sectionHead"><div><span className="sectionKicker">WHY POINTPILOT</span><h2>Optimisation you can audit</h2><p>The recommendation is only as good as the rule behind it.</p></div></div>
 <section className="featureGrid"><article className="feature"><div className="icon">◎</div><h3>Your wallet, not a generic ranking</h3><p>Recommendations start with cards, points and miles you actually hold.</p></article><article className="feature"><div className="icon">₹</div><h3>Real value after friction</h3><p>Taxes, fees, caps, transfer ratios and cash remaining stay visible.</p></article><article className="feature"><div className="icon">✓</div><h3>Sources before claims</h3><p>Issuer rules carry verification context; cash inventory never becomes a pretend award seat.</p></article></section>
 <section className="homeCta"><div><span className="sectionKicker">READY WHEN YOU ARE</span><h2>Make your next reward decision count.</h2><p>Build your wallet once. Use it across every spend, redemption and trip.</p></div><Link className="btn primary" href="/login">Start free →</Link></section>
 <footer>PointPilot • Every spend. Every point. One smarter decision.</footer>
</main>}
