"use client";
import {useEffect,useMemo,useState} from "react";
import {getSupabase} from "../../lib/supabase-browser.js";
import {AIRLINE_PROGRAMS,AIRLINE_PROGRAMS_REVIEWED_AT,programForPartner} from "../../lib/airline-programs.js";

const fmt=n=>Number(n||0).toLocaleString("en-IN");
const clean=v=>String(v||"").toLowerCase().replace(/credit card|metal card|card|club|first|hdfc|icici|idfc|bank|american express india|scapia federal|federal/g,"").replace(/[^a-z0-9]/g,"");
const matches=(cardName,rule)=>{const a=clean(cardName),b=clean(rule?.card_name);return Boolean(b&&(a.includes(b)||b.includes(a)))};
const ratioText=ratio=>{const n=Number(ratio);if(!Number.isFinite(n)||n<=0)return "rate unavailable";if(Math.abs(n-1)<.0001)return "1:1";if(n>1)return `${n.toFixed(n%1?2:0).replace(/0$/,"")}:1`;const received=1/n;return `1:${received.toFixed(received%1?2:0).replace(/0$/,"")}`};
const daysUntil=value=>value?Math.ceil((new Date(`${value}T23:59:59`).getTime()-Date.now())/86400000):null;

export default function AirlineMiles({wallet}){
 const[balances,setBalances]=useState([]),[rules,setRules]=useState([]),[showAdd,setShowAdd]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const[form,setForm]=useState({program_code:AIRLINE_PROGRAMS[0].code,miles:"",expiry_date:""});
 const[quote,setQuote]=useState({program_code:AIRLINE_PROGRAMS[0].code,cashFare:75000,taxes:8500,milesRequired:45000});
 useEffect(()=>{let active=true;(async()=>{const sb=getSupabase();const{data:{user}}=await sb.auth.getUser();if(!user)return;const[{data:b,error:balanceError},{data:r}]=await Promise.all([sb.from("airline_mile_balances").select("*").eq("user_id",user.id).order("created_at"),sb.from("reward_rules").select("*").eq("active",true).eq("partner_type","airline_transfer").order("partner")]);if(!active)return;if(balanceError&&balanceError.code!=="42P01"&&balanceError.code!=="PGRST205")setError(balanceError.message);setBalances(b||[]);setRules(r||[])})().catch(err=>{if(active)setError(err?.message||"Unable to load airline miles.")});return()=>{active=false}},[]);
 const totalMiles=balances.reduce((sum,row)=>sum+Number(row.miles||0),0);
 const selected=AIRLINE_PROGRAMS.find(p=>p.code===quote.program_code)||AIRLINE_PROGRAMS[0];
 const net=Math.max(0,Number(quote.cashFare||0)-Number(quote.taxes||0));
 const perMile=Number(quote.milesRequired)>0?net/Number(quote.milesRequired):0;
 const owned=balances.find(row=>row.program_code===quote.program_code);
 const shortfall=Math.max(0,Number(quote.milesRequired||0)-Number(owned?.miles||0));
 const verdict=perMile>=2.5?"Exceptional value":perMile>=1.5?"Strong value":perMile>=.8?"Consider the trade-off":"Cash may be better";
 const transferRoutes=useMemo(()=>rules.map(rule=>{const program=programForPartner(rule.partner);if(!program)return null;const card=wallet.find(item=>matches(item.card_name,rule));if(!card)return null;const ratio=Number(rule.transfer_ratio||0);const transferable=ratio>0?Math.floor(Number(card.points||0)/ratio):0;return{rule,program,card,transferable}}).filter(Boolean).sort((a,b)=>b.transferable-a.transferable),[rules,wallet]);
 const addBalance=async e=>{e.preventDefault();setError("");setSaving(true);const sb=getSupabase();const{data:{user}}=await sb.auth.getUser();if(!user){location.replace("/login");return}const payload={user_id:user.id,program_code:form.program_code,miles:Math.round(Number(form.miles)||0),expiry_date:form.expiry_date||null,updated_at:new Date().toISOString()};const{data,error:saveError}=await sb.from("airline_mile_balances").upsert(payload,{onConflict:"user_id,program_code"}).select().single();setSaving(false);if(saveError){setError(saveError.code==="42P01"||saveError.code==="PGRST205"?"The airline-miles ledger is being activated. Refresh after the database update completes.":saveError.message);return}setBalances(previous=>[...previous.filter(row=>row.program_code!==data.program_code),data]);setShowAdd(false);setForm({...form,miles:"",expiry_date:""})};
 const remove=async id=>{if(!window.confirm("Remove this airline miles balance?"))return;const{error:removeError}=await getSupabase().from("airline_mile_balances").delete().eq("id",id);if(removeError){setError(removeError.message);return}setBalances(previous=>previous.filter(row=>row.id!==id))};
 return <section className="airMiles" id="airline-miles"><div className="sectionHead milesHead"><div><span className="sectionKicker">AIRLINE MILES INTELLIGENCE</span><h2>Turn balances into award flights.</h2><p>Track airline miles, expose card-transfer paths and test a real award quote against its cash fare.</p></div><div className="milesTotal"><small>AIRLINE MILES</small><strong>{fmt(totalMiles)}</strong><span>{balances.length} programme{balances.length===1?"":"s"}</span></div></div>
 <div className="milesWorkbench"><article className="milesLedger"><div className="milesPanelTop"><div><small>01 / BALANCE LEDGER</small><h3>Your airline programmes</h3></div><button className="btn primary" onClick={()=>{setError("");setShowAdd(!showAdd)}}>{showAdd?"Close":"＋ Add miles"}</button></div>
 {showAdd&&<form className="milesForm" onSubmit={addBalance}><label>Programme<select value={form.program_code} onChange={e=>setForm({...form,program_code:e.target.value})}>{AIRLINE_PROGRAMS.map(program=><option value={program.code} key={program.code}>{program.airline} · {program.name}</option>)}</select></label><label>Current miles<input required type="number" min="0" value={form.miles} onChange={e=>setForm({...form,miles:e.target.value})}/></label><label>Nearest expiry (optional)<input type="date" value={form.expiry_date} onChange={e=>setForm({...form,expiry_date:e.target.value})}/></label><button className="btn primary" disabled={saving}>{saving?"Saving…":"Save balance"}</button></form>}
 {error&&<div className="errorBox">{error}</div>}{!balances.length&&!showAdd&&<div className="milesEmpty">Add the balances you already hold. PointPilot never asks for or stores your airline password or membership number.</div>}
 <div className="milesBalanceGrid">{balances.map(row=>{const program=AIRLINE_PROGRAMS.find(p=>p.code===row.program_code);if(!program)return null;const days=daysUntil(row.expiry_date);return <article key={row.id}><div className="airlineMark">{program.initials}</div><div><small>{program.airline}</small><b>{program.name}</b><strong>{fmt(row.miles)} <i>{program.currency}</i></strong>{days!=null&&<span className={days<=90?"expirySoon":""}>{days<0?"Expiry date passed":days===0?"Expires today":`Nearest expiry in ${days} days`}</span>}</div><button className="linkBtn" onClick={()=>remove(row.id)}>Remove</button></article>})}</div></article>
 <article className="awardLab"><div className="milesPanelTop"><div><small>02 / AWARD VALUE LAB</small><h3>Is this award worth booking?</h3></div><span className="sourceStatus">MANUAL AWARD QUOTE</span></div><div className="awardInputs"><label>Programme<select value={quote.program_code} onChange={e=>setQuote({...quote,program_code:e.target.value})}>{AIRLINE_PROGRAMS.map(program=><option value={program.code} key={program.code}>{program.name}</option>)}</select></label><label>Comparable cash fare (₹)<input type="number" min="0" value={quote.cashFare} onChange={e=>setQuote({...quote,cashFare:e.target.value})}/></label><label>Taxes and fees (₹)<input type="number" min="0" value={quote.taxes} onChange={e=>setQuote({...quote,taxes:e.target.value})}/></label><label>Miles required<input type="number" min="1" value={quote.milesRequired} onChange={e=>setQuote({...quote,milesRequired:e.target.value})}/></label></div><div className="awardVerdict"><div><small>NET VALUE PER MILE</small><strong>₹{perMile.toFixed(2)}</strong><span>{verdict}</span></div><div className="awardMath"><b>₹{fmt(net)} net cash value</b><span>₹{fmt(quote.cashFare)} fare − ₹{fmt(quote.taxes)} unavoidable taxes</span><b>{owned?`${fmt(owned.miles)} miles held`:`No ${selected.name} balance added`}</b><span>{shortfall>0?`${fmt(shortfall)} miles short before any transfer`:`Current balance covers this quote`}</span></div></div><a className="awardSearch" href={selected.award_search_url} target="_blank" rel="noreferrer">Check live award availability with {selected.airline} <span>↗</span></a><p className="awardGuardrail">The quote is entered by you. PointPilot calculates value and sufficiency, but labels an award seat confirmed only after the airline or an authorised award source confirms it.</p></article></div>
 <div className="transferMap"><div className="milesPanelTop"><div><small>03 / TRANSFER MAP</small><h3>Routes from cards you already hold</h3></div><span className="sourceStatus">VERIFIED ISSUER RULES</span></div>{transferRoutes.length?<div className="transferGrid">{transferRoutes.slice(0,8).map(({rule,program,card,transferable},index)=><article key={rule.id||index}><div className="airlineMark">{program.initials}</div><div><b>{card.card_name} → {program.name}</b><span>{ratioText(rule.transfer_ratio)} • up to {fmt(transferable)} {program.currency} from the current card balance</span><small>{rule.transfer_time||"Transfer time not supplied—verify before moving points."}</small></div><a href={rule.source_url} target="_blank" rel="noreferrer">Source ↗</a></article>)}</div>:<div className="milesEmpty">No verified airline-transfer route matches the cards currently in your wallet.</div>}</div>
 <div className="programmeShelf"><div className="milesPanelTop"><div><small>PROGRAMME DIRECTORY · REVIEWED {AIRLINE_PROGRAMS_REVIEWED_AT}</small><h3>12 useful award currencies for India-based travellers</h3></div><span className="sourceStatus">OFFICIAL SOURCES</span></div><div className="programmeGrid">{AIRLINE_PROGRAMS.map(program=><article key={program.code}><div className="programmeTitle"><span>{program.initials}</span><div><small>{program.alliance}</small><b>{program.name}</b></div></div><p>{program.summary}</p><div><span>{program.region}</span><a href={program.source_url} target="_blank" rel="noreferrer">Programme rules ↗</a></div></article>)}</div></div>
 </section>
}
