"use client";
import {useEffect,useMemo,useState} from "react";
import {createClient} from "@supabase/supabase-js";
const getSupabase=()=>createClient(process.env.NEXT_PUBLIC_SUPABASE_URL,process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY);
function clean(v){return String(v||"").toLowerCase().replace(/credit card|metal card|card|club|first|hdfc|icici|idfc|bank|american express india|scapia federal|federal/g,"").replace(/[^a-z0-9]/g,"")}
function matches(cardName,rule){const a=clean(cardName),b=clean(rule?.card_name);return Boolean(b&&(a.includes(b)||b.includes(a)))}
function fmt(n){return Number(n||0).toLocaleString("en-IN")}
function routeLabel(r){if(r.partner_type==="direct_travel")return "Direct travel";if(r.partner_type==="voucher")return "Voucher";if(r.partner_type==="hotel_transfer")return "Hotel transfer";if(r.partner_type==="airline_transfer")return "Airline transfer";return r.partner_type||"Redemption"}
function ratioText(r){const n=Number(r);if(!Number.isFinite(n)||n<=0)return "Route loaded";if(Math.abs(n-1)<.0001)return "1:1";const received=1/n;return "1:"+received.toFixed(received%1?1:0)}
export default function BestUseSection({wallet}){
 const[rules,setRules]=useState([]),[loading,setLoading]=useState(true);
 useEffect(()=>{getSupabase().from("reward_rules").select("*").eq("active",true).order("issuer").order("partner").then(({data})=>{setRules(data||[]);setLoading(false)})},[]);
 const options=useMemo(()=>{const rows=[];for(const w of wallet){const balance=Number(w.points||0);if(balance<=0)continue;for(const r of rules.filter(x=>matches(w.card_name,x))){const rate=Number(r.redemption_value);if((r.partner_type==="direct_travel"||r.partner_type==="voucher")&&rate>0){const max=Number(r.max_redeem_points||balance);const usable=Math.min(balance,max);rows.push({card:w.card_name,balance,partner:r,type:routeLabel(r),rate,maxPoints:usable,value:usable*rate,verified:r.verified_at,source:r.source_url,note:r.notes})}else if(r.partner_type==="hotel_transfer"||r.partner_type==="airline_transfer"){rows.push({card:w.card_name,balance,partner:r,type:routeLabel(r),rate:null,ratio:r.transfer_ratio,verified:r.verified_at,source:r.source_url,note:r.notes})}}}return rows.sort((a,b)=>(b.value||0)-(a.value||0))},[wallet,rules]);
 const direct=options.filter(x=>x.rate).slice(0,4),transfers=options.filter(x=>!x.rate).slice(0,4);
 const total=wallet.reduce((a,x)=>a+Number(x.points||0),0);
 return <section className="bestUse"><div className="sectionHead"><div><h2>Best use of your points</h2><p>PointPilot turns your wallet into actionable redemption routes.</p></div><span className="engineBadge">OPTIMIZATION ENGINE</span></div>{loading?<div className="notice">Loading your verified redemption rules…</div>:!options.length?<div className="notice">No verified redemption route is loaded for this wallet yet.</div>:<div className="bestUseGrid"><article className="optimizerHero"><small>YOUR WALLET</small><strong>{fmt(total)}</strong><span>points across {wallet.length} cards</span><div className="optimizerRule">We compare redemption value, usable balance, caps and route status. Award availability is never assumed.</div></article><div className="useList"><h3>Direct value you can use today</h3>{direct.length?direct.map((x,i)=><div className="useRow" key={x.card+x.partner.partner+i}><div><b>{x.card}</b><span>{x.partner.partner} • {x.type}</span></div><div className="useValue"><strong>₹{x.rate.toFixed(2)}/pt</strong><span>up to ₹{fmt(x.value)} from current balance</span></div></div>):<div className="emptyMini">No fixed direct-value route available.</div>}</div><div className="useList"><h3>Transfer routes to watch</h3>{transfers.length?transfers.map((x,i)=><div className="useRow" key={x.card+x.partner.partner+i}><div><b>{x.card}</b><span>{x.partner.partner} • {x.type}</span></div><div className="useValue"><strong>{ratioText(x.ratio)}</strong><span>Check live award availability before transferring.</span></div></div>):<div className="emptyMini">No airline/hotel transfer route loaded.</div>}</div></div>}</section>
}