"use client";
import {fundingStatus} from "../../lib/funding-status.js";
import {bestFlightRedemption} from "../../lib/booking-decision.js";
import BookingComparison from "./BookingComparison.js";
import {useEffect,useMemo,useState} from "react";
import {getSupabase} from "../../lib/supabase-browser.js";
import {AIRLINE_PROGRAMS} from "../../lib/airline-programs.js";
import {buildAwardFunding,buildDirectRedemptions,redemptionRouteLabel,transferRatioText} from "../../lib/reward-planner.js";
function fmt(n){return Number(n||0).toLocaleString("en-IN")}
export default function BestUseSection({wallet}){
 const[revision,setRevision]=useState(0);
 useEffect(()=>{const refresh=()=>setRevision(v=>v+1);window.addEventListener("pointpilot:miles-changed",refresh);return()=>window.removeEventListener("pointpilot:miles-changed",refresh)},[]);
 const[rules,setRules]=useState([]),[balances,setBalances]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const[target,setTarget]=useState({cashFare:75000,taxes:8500,milesRequired:45000,programCode:"air-india-maharaja"});
 useEffect(()=>{let active=true;(async()=>{const sb=getSupabase();const{data:{user},error:userError}=await sb.auth.getUser();if(userError)throw userError;if(!user)return;const[{data:r,error:ruleError},{data:b,error:balanceError}]=await Promise.all([sb.from("reward_rules").select("*").eq("active",true).order("issuer").order("partner"),sb.from("airline_mile_balances").select("*").eq("user_id",user.id)]);if(ruleError)throw ruleError;if(balanceError&&!['42P01','PGRST205'].includes(balanceError.code))throw balanceError;if(active){setRules(r||[]);setBalances(b||[]);setLoading(false)}})().catch(error=>{if(active){setError(error?.message||"Unable to load redemption routes.");setLoading(false)}});return()=>{active=false}},[revision]);
 const direct=useMemo(()=>buildDirectRedemptions(wallet,rules,target.cashFare),[wallet,rules,target.cashFare]);
 const award=useMemo(()=>buildAwardFunding({wallet,rules,balances,programCode:target.programCode,milesRequired:target.milesRequired,cashFare:target.cashFare,taxes:target.taxes}),[wallet,rules,balances,target]);
 const funding=fundingStatus(award);
 const flightDirect=bestFlightRedemption(direct);
 const recommendation=funding.covered&&award.valuePerMile>=1.5?{title:"Check the award seat first",copy:`Your balances can fund this ${award.program.name} target at a modeled ₹${award.valuePerMile.toFixed(2)} per mile. Confirm the seat and total taxes before transferring.`}:flightDirect?.value>0?{title:`Use ${flightDirect.card.card_name} as the cash-value benchmark`,copy:`Its flight-eligible ${flightDirect.rule.partner} route can offset up to ₹${fmt(flightDirect.value)} on this target. Compare that with the live award quote before moving points.`}:{title:"Keep the points flexible",copy:"This wallet does not yet have enough verified data to recommend a transfer. Add balances or use a sourced route before committing points."};
 const total=wallet.reduce((a,x)=>a+Number(x.points||0),0);
 const update=(key,value)=>setTarget(previous=>({...previous,[key]:value}));
 return <section className="bestUse"><div className="sectionHead"><div><span className="sectionKicker">POINTS DEPLOYMENT PLAN</span><h2>Turn one trip into a clear decision.</h2><p>Compare direct redemption, airline miles and card transfers against the same target—without pretending a cash seat is an award seat.</p></div><span className="engineBadge">LIVE WALLET · VERIFIED ROUTES</span></div>
 {loading?<div className="notice">Building your private redemption plan…</div>:error?<div className="errorBox">We couldn’t load the route catalogue: {error}</div>:<><div className="redemptionInputs"><label>Comparable cash fare<div><em>₹</em><input type="number" min="0" value={target.cashFare} onChange={event=>update("cashFare",event.target.value)}/></div></label><label>Airline programme<select value={target.programCode} onChange={event=>update("programCode",event.target.value)}>{AIRLINE_PROGRAMS.map(program=><option value={program.code} key={program.code}>{program.airline} · {program.name}</option>)}</select></label><label>Award miles required<input type="number" min="0" value={target.milesRequired} onChange={event=>update("milesRequired",event.target.value)}/></label><label>Taxes and fees<div><em>₹</em><input type="number" min="0" value={target.taxes} onChange={event=>update("taxes",event.target.value)}/></div></label></div>
 <BookingComparison cashFare={target.cashFare} taxes={target.taxes} award={award} direct={direct}/>
 <div className="deploymentGrid"><article className="deploymentSummary"><small>YOUR DEPLOYMENT PLAN</small><strong>{fmt(total)} <i>card points</i></strong><div className="coverageRing" style={{"--coverage":`${Math.round(award.coverage*100)}%`}}><span>{Math.round(award.coverage*100)}%</span><small>{funding.coverageLabel}</small></div><p>{funding.warning}</p><p>{recommendation.title}</p><span>{recommendation.copy}</span></article><article className="deploymentCard"><div className="deploymentCardTop"><span>01</span><div><small>FLIGHT CASH-VALUE BENCHMARK</small><h3>{flightDirect?.rule.partner||"No fixed-value route"}</h3></div></div>{flightDirect?<><dl><div><dt>Use</dt><dd>{flightDirect.card.card_name}</dd></div><div><dt>Points</dt><dd>{fmt(flightDirect.pointsUsed)}</dd></div><div><dt>Value protected</dt><dd>₹{fmt(flightDirect.value)}</dd></div><div><dt>Cash remaining</dt><dd>₹{fmt(flightDirect.cashRemaining)}</dd></div></dl><a href={flightDirect.rule.source_url} target="_blank" rel="noreferrer">Verify issuer route ↗</a></>:<p className="deploymentEmpty">No verified flight-specific fixed-value route matches this wallet yet.</p>}</article><article className="deploymentCard"><div className="deploymentCardTop"><span>02</span><div><small>AIRLINE AWARD FUNDING</small><h3>{award.program.name}</h3></div></div><dl><div><dt>Miles held</dt><dd>{fmt(award.existing)}</dd></div><div><dt>{funding.transferLabel}</dt><dd>{fmt(award.plannedTransfer)}</dd></div><div><dt>Remaining gap</dt><dd className={award.shortfall?"gap":"covered"}>{fmt(award.shortfall)}</dd></div><div><dt>Modeled value</dt><dd>₹{award.valuePerMile.toFixed(2)}/mile</dd></div></dl><a href={award.program.award_search_url} target="_blank" rel="noreferrer">Check live award availability ↗</a></article></div>
 <div className="routeWorkbench"><div className="routeColumn"><div className="routeColumnHead"><div><small>DIRECT REDEMPTION RANKING</small><h3>What your card points can buy</h3></div><span>{direct.length} verified option{direct.length===1?"":"s"}</span></div>{direct.slice(0,5).map((item,index)=><article className="deploymentRoute" key={`${item.card.id||item.card.card_name}-${item.rule.id||index}`}><i>0{index+1}</i><div><b>{item.card.card_name}</b><span>{item.rule.partner} · {item.type}</span><small>{item.rule.notes}</small></div><strong>₹{fmt(item.value)}<small>₹{item.rate.toFixed(2)}/pt</small></strong></article>)}{!direct.length&&<div className="deploymentEmpty">No fixed direct-value route is available for this wallet.</div>}</div><div className="routeColumn"><div className="routeColumnHead"><div><small>TRANSFER SEQUENCE</small><h3>How to close the award gap</h3></div><span>{award.program.initials}</span></div>{award.routes.filter(item=>item.transferable>0).slice(0,5).map((item,index)=><article className="deploymentRoute" key={`${item.card.id||item.card.card_name}-${item.rule.id||index}`}><i>0{index+1}</i><div><b>{item.card.card_name} → {award.program.name}</b><span>{transferRatioText(item.ratio)} · up to {fmt(item.transferable)} miles estimated · {item.limitsStatus==="verified"?"limits modeled":"limits unverified"}</span><small>{item.contribution>0?`Estimate: ${fmt(item.pointsNeeded)} points for ${fmt(item.milesReceived??item.contribution)} miles received; ${fmt(item.contribution)} applied to the target. Confirm transfer limits and award space first.`:"No transfer allocated to this route. Verify its limits before use."}</small></div><strong>{fmt(item.contribution)}<small>estimated miles used</small></strong></article>)}{!award.routes.some(item=>item.transferable>0)&&<div className="deploymentEmpty">No verified transfer route to this programme matches the cards in this wallet.</div>}</div></div><div className="redemptionGuardrail"><b>Before any transfer</b><span>Open the airline award search, confirm the exact flight, cabin, mileage and taxes, then transfer only what is needed. Transfers may be irreversible and PointPilot never labels cash availability as award availability.</span></div></>}
 </section>
}
