"use client";
import {useState} from "react";
import {buildBookingDecision,bookingFeeTotals,flightRouteStatus} from "../../lib/booking-decision.js";
import PersonalValue from "./PersonalValue.js";

const fmt=value=>Number(value||0).toLocaleString("en-IN",{maximumFractionDigits:2});
export default function BookingComparison({cashFare,taxes,award,direct}){
 const [selected,setSelected]=useState("");
 const [feeScenarios,setFeeScenarios]=useState({});
 const options=direct.filter(item=>flightRouteStatus(item.rule)==="flight_candidate");
 const excluded=direct.filter(item=>flightRouteStatus(item.rule)!=="flight_candidate");
 const route=options.find(item=>(item.card.id||item.card.card_name)+"|"+(item.rule.id||item.rule.partner)===selected)||options[0];
 const feeKey=(route?.card.id||route?.card.card_name||"none")+"|"+(route?.rule.id||route?.rule.partner||"none")+"|"+award.program.code;
 const extraFees=feeScenarios[feeKey]||{cash:0,direct:0,award:0,transfer:0};
 const extras=bookingFeeTotals(extraFees);
 const cash=Number(cashFare),fees=Number(taxes);
 const valid=Boolean(extras)&&Number.isFinite(cash)&&cash>0&&Number.isFinite(fees)&&fees>=0;
 const funded=award.target>0&&award.shortfall===0;
 const transfers=award.routes.filter(item=>item.contribution>0);
 const decision=buildBookingDecision({cashFare,taxes,award,direct:route,extraFees});
 return <section className="bookingCompare" aria-label="Compare ways to book">
  <div className="sectionHead"><div><span className="sectionKicker">COMPARE WAYS TO BOOK</span><h3>One trip. Three ways to pay.</h3><p>Use quotes for the same flights, cabin and travellers. Values below are estimates from your inputs, not booking offers.</p></div></div>
  <details className="personalValue"><summary>Add booking and transfer fees</summary><p>Only add charges not already included in the fare or award taxes. Amounts are total INR for all travellers. Zero means no extra fee assumed—not a verified fee quote. Recheck these inputs when changing the trip; they are not saved.</p><div className="valueInputs">{[["cash","Cash booking fee"],["direct","Card redemption / portal fee"],["award","Award booking fee"],["transfer","Total card-to-airline transfer fees"]].map(([key,label])=><label key={key}>{label} (₹)<input type="number" min="0" step="0.01" value={extraFees[key]} onChange={event=>setFeeScenarios(previous=>({...previous,[feeKey]:{...extraFees,[key]:event.target.value}}))}/></label>)}</div><button type="button" onClick={()=>setFeeScenarios(previous=>({...previous,[feeKey]:{cash:0,direct:0,award:0,transfer:0}}))}>Reset extra fees</button></details>
  {!valid?<div className="notice">Enter a positive cash fare and valid non-negative taxes and extra fees. Blank fees must be entered as zero if none apply.</div>:<>
  {decision&&<div className="bookingDecision" aria-live="polite"><small>YOUR NEXT CHECK · NOT A BOOKING RECOMMENDATION</small><h4>{decision.lowest.kind==="award"?"Check the airline award first":decision.lowest.kind==="direct"?"Check the selected card route first":"Keep cash as your benchmark"}</h4><p>{decision.lowest.kind==="cash"?"Cash has the lowest or equal out-of-pocket cost among the eligible scenarios and preserves your points.":`This scenario has the lowest modeled cash payment: ₹${fmt(decision.lowest.cash)}, or ₹${fmt(decision.cashSaved)} less cash than the cash booking including entered fees. Points consumed are not free, so this is not a best-value ranking.`}</p>{decision.awardValue!=null&&<p>The award offsets ₹{decision.awardValue.toFixed(2)} per mile after entered taxes and extra fees. Compare this with what those miles—and any card points transferred—are worth to you. Only the fees you enter are included; lost earning and cancellation costs are excluded.</p>}{decision.reason&&<p>{decision.reason==="funding"?"The award is excluded from the lowest-cash comparison until its mileage target is fully funded.":"The award is excluded because a required transfer route or its minimums, increments and caps still need verification."}</p>}<p>Before paying or transferring: confirm identical flights and baggage, the final portal price, award space, transfer eligibility and cancellation terms.</p></div>}
  <div className="bookingOptions">
   <article><small>CASH</small><h4>Keep your points</h4><strong>₹{fmt(cash+extras.cash)}</strong><span>Cash payable · fare plus entered fees</span><dl><dt>Points used</dt><dd>None</dd><dt>Points retained</dt><dd>All balances</dd></dl><p>Check baggage, cancellation terms and the final checkout total. Future points earned are excluded.</p></article>
   <article><small>DIRECT CARD REDEMPTION</small><h4>Use a card redemption route</h4>{route?<><label>Compare route<select value={(route.card.id||route.card.card_name)+"|"+(route.rule.id||route.rule.partner)} onChange={e=>setSelected(e.target.value)}>{options.map((item,index)=><option key={index} value={(item.card.id||item.card.card_name)+"|"+(item.rule.id||item.rule.partner)}>{item.card.card_name} · {item.rule.partner}</option>)}</select></label><strong>₹{fmt(route.cashRemaining+extras.direct)}</strong><span>Estimated cash payable including entered portal fees</span><dl><dt>Card points used</dt><dd>{fmt(route.pointsUsed)} · {route.card.card_name}</dd><dt>Fare offset</dt><dd>₹{fmt(route.value)}</dd><dt>Effective value</dt><dd>₹{route.rate.toFixed(2)}/point</dd></dl><p>{route.rule.notes||"Issuer eligibility, redemption caps and booking conditions apply."} Confirm this route covers your selected airline and fare. Portal prices may differ from the cash quote; voucher residual value is excluded.</p>{route.rule.source_url&&<a href={route.rule.source_url} target="_blank" rel="noreferrer">Check issuer terms ↗</a>}</>:<p>No verified flight-specific fixed-value route matches this wallet. Add a supported card or compare cash with an airline award.</p>}</article>
   <article><small>AIRLINE AWARD</small><h4>{award.program.name}</h4><strong>{award.target>0?"₹"+fmt(fees+extras.award+extras.transfer):"Quote needed"}</strong><span>{funded?decision?.awardEligible?"Cash payable if the quoted award is available":"Taxes and fees · transfer rules unverified":"Taxes and entered fees only · funding incomplete"}</span><dl><dt>Airline miles redeemed</dt><dd>{fmt(award.target)}</dd><dt>Existing miles used</dt><dd>{fmt(Math.min(award.existing,award.target))}</dd><dt>Miles still needed</dt><dd>{fmt(award.shortfall)}</dd></dl>{transfers.map((item,index)=><p key={index}>{item.limitsStatus==="verified"?"Modeled transfer":"Ratio-only estimate"}: {fmt(item.pointsNeeded)} {item.card.card_name} points → {fmt(item.milesReceived??item.contribution)} miles. {item.surplusMiles>0&&`${fmt(item.contribution)} used for this award; ${fmt(item.surplusMiles)} extra miles remain after block rounding.`} {item.limitsStatus!=="verified"&&"Transfer units, minimums, increments and caps need verification before this can be a usable funding plan."}</p>)}<p>{!funded?"The missing miles are not priced here; this is not a fully funded booking option. ":"Funding is modeled, not a seat confirmation. "}Confirm award space, total taxes, transfer minimums, increments and timing. Transfers may be irreversible; cancellation rules differ.</p><a href={award.program.award_search_url} target="_blank" rel="noreferrer">Check airline award quote ↗</a></article>
  </div><p className="bookingNote">Compare the cash you retain with the points you give up. A lower cash payment does not automatically mean better value. These options are alternatives: the same points cannot fund two options at once.</p>
  {excluded.length>0&&<details className="personalValue"><summary>{excluded.length} routes excluded from this flight comparison</summary><p>Only routes whose loaded terms identify flight use enter this comparison. This does not confirm eligibility for your specific flight.</p><ul>{excluded.map((item,index)=><li key={index}>{item.card.card_name} · {item.rule.partner}: {({hotel_only:"hotel-only route",statement_credit:"statement credit—not a reduction in checkout cash",unverified:"not verified or inactive",unsupported:"not a direct flight redemption",needs_verification:"flight eligibility needs verification"})[flightRouteStatus(item.rule)]}.</li>)}</ul></details>}
  <PersonalValue decision={decision} direct={route} award={award}/>
  </>}
 </section>;
}
