"use client";

import {useEffect,useMemo,useState} from "react";
import {getSupabase} from "../../lib/supabase-browser.js";
const money=value=>Number(value||0).toLocaleString("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0});
const clean=value=>String(value||"").toLowerCase().replace(/credit card|metal edition|metal card|card|club|first|hdfc|icici|idfc|bank|american express india/g,"").replace(/[^a-z0-9]/g,"");
const matches=(left,right)=>{const a=clean(left),b=clean(right);return Boolean(a&&b&&(a.includes(b)||b.includes(a)))};
const currentYearStart=()=>`${new Date().getFullYear()}-01-01`;
const currentQuarterStart=()=>{const now=new Date();return `${now.getFullYear()}-${String(Math.floor(now.getMonth()/3)*3+1).padStart(2,"0")}-01`};

export default function MilestoneTracker({wallet,userId}){
 const[rules,setRules]=useState([]),[progress,setProgress]=useState({}),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[saved,setSaved]=useState(false),[error,setError]=useState("");
 useEffect(()=>{if(!userId)return;let active=true;(async()=>{const sb=getSupabase();const[{data:ruleRows,error:ruleError},{data:progressRows,error:progressError}]=await Promise.all([sb.from("card_milestone_rules").select("*").eq("active",true).order("target_amount"),sb.from("user_card_spend_progress").select("*").eq("user_id",userId)]);if(!active)return;if(ruleError)throw ruleError;if(progressError)throw progressError;setRules(ruleRows||[]);setProgress(Object.fromEntries((progressRows||[]).map(row=>[row.wallet_card_id,row])));setLoading(false)})().catch(err=>{if(active){setError(err?.message||"Unable to load milestone tracking.");setLoading(false)}});return()=>{active=false}},[userId]);
 const tracked=useMemo(()=>wallet.map(card=>({card,rules:rules.filter(rule=>matches(card.card_name,rule.card_name)),entry:progress[card.id]||{annual_spend:0,quarterly_spend:0,cycle_start:currentYearStart(),quarter_start:currentQuarterStart()}})).filter(row=>row.rules.length),[wallet,rules,progress]);
 const summary=useMemo(()=>{const evaluated=tracked.flatMap(row=>row.rules.map(rule=>{const amount=Number(row.entry[rule.progress_field]||0);return{...rule,amount,remaining:Math.max(0,Number(rule.target_amount)-amount),ratio:Math.min(1,amount/Number(rule.target_amount))}}));const achieved=evaluated.filter(rule=>rule.remaining===0);const next=evaluated.filter(rule=>rule.remaining>0).sort((a,b)=>b.ratio-a.ratio)[0];return{achieved:achieved.length,total:evaluated.length,next,protectedValue:achieved.filter(rule=>rule.rule_type==="fee_waiver").reduce((sum,rule)=>sum+Number(rule.estimated_value||0),0)}} ,[tracked]);
 const update=(cardId,field,value)=>{setSaved(false);setProgress(previous=>({...previous,[cardId]:{...(previous[cardId]||{}),[field]:field.includes("spend")?Math.max(0,Number(value)||0):value}}))};
 const save=async()=>{setSaving(true);setSaved(false);setError("");const rows=tracked.map(({card,entry})=>({wallet_card_id:card.id,user_id:userId,annual_spend:Math.max(0,Number(entry.annual_spend)||0),quarterly_spend:Math.max(0,Number(entry.quarterly_spend)||0),cycle_start:entry.cycle_start||null,quarter_start:entry.quarter_start||null,updated_at:new Date().toISOString()}));if(!rows.length){setSaving(false);return}const{error:saveError}=await getSupabase().from("user_card_spend_progress").upsert(rows,{onConflict:"wallet_card_id"});setSaving(false);if(saveError){setError(saveError.message);return}setSaved(true)};
 return <section className="milestoneTracker" id="milestones">
  <div className="sectionHead milestoneHead"><div><span className="sectionKicker">MILESTONES &amp; FEE WAIVERS</span><h2>Know the next threshold worth chasing.</h2><p>Track statement spend against verified targets, without moving spend blindly just to reach a milestone.</p></div><span className="planPreview">PRO PREVIEW</span></div>
  {loading?<div className="notice">Loading your verified thresholds…</div>:error&&!rules.length?<div className="errorBox">{error}</div>:tracked.length?<>
   <div className="milestoneSummary"><div><small>TRACKED CARDS</small><strong>{tracked.length}</strong></div><div><small>THRESHOLDS REACHED</small><strong>{summary.achieved}/{summary.total}</strong></div><div><small>FEES PROTECTED</small><strong>{money(summary.protectedValue)}</strong></div><div className="nextTarget"><small>CLOSEST NEXT TARGET</small><strong>{summary.next?money(summary.next.remaining):"All reached"}</strong><span>{summary.next?`remaining for ${summary.next.card_name}`:"Confirm benefits with each issuer"}</span></div></div>
   <div className="milestoneCards">{tracked.map(({card,rules:cardRules,entry})=><article key={card.id} className="milestoneCard"><div className="milestoneCardTop"><div><small>{cardRules[0].issuer}</small><h3>{card.card_name}</h3></div><span>{cardRules.length} verified target{cardRules.length===1?"":"s"}</span></div><div className="progressInputs"><label>Annual cycle spend<div><em>₹</em><input type="number" min="0" step="1000" value={entry.annual_spend||""} placeholder="0" onChange={event=>update(card.id,"annual_spend",event.target.value)}/></div></label><label>Current-quarter spend<div><em>₹</em><input type="number" min="0" step="1000" value={entry.quarterly_spend||""} placeholder="0" onChange={event=>update(card.id,"quarterly_spend",event.target.value)}/></div></label><label>Annual cycle began<input type="date" value={entry.cycle_start||currentYearStart()} onChange={event=>update(card.id,"cycle_start",event.target.value)}/></label><label>Quarter began<input type="date" value={entry.quarter_start||currentQuarterStart()} onChange={event=>update(card.id,"quarter_start",event.target.value)}/></label></div><div className="thresholdList">{cardRules.map(rule=>{const amount=Number(entry[rule.progress_field]||0),target=Number(rule.target_amount),remaining=Math.max(0,target-amount),percent=Math.min(100,target?amount/target*100:0);return <div className={`threshold ${remaining===0?"reached":""}`} key={rule.id}><div className="thresholdTop"><span>{rule.rule_type==="fee_waiver"?"FEE WAIVER":"MILESTONE"} · {rule.cadence.toUpperCase()}</span><b>{remaining===0?"Threshold reached":`${money(remaining)} to go`}</b></div><div className="progressTrack"><i style={{width:`${percent}%`}}/></div><div className="thresholdFoot"><span>{money(amount)} / {money(target)}</span><strong>{rule.reward_text}</strong></div><small>Verified {rule.verified_at} · <a href={rule.source_url} target="_blank" rel="noreferrer">issuer source ↗</a></small></div>})}</div></article>)}</div>
   <div className="milestoneSave"><button onClick={save} disabled={saving}>{saving?"Saving progress…":"Save milestone progress"}</button>{saved&&<span>✓ Progress saved securely</span>}{error&&<span className="planError">{error}</span>}</div>
  </>:<div className="milestoneEmpty"><strong>No verified milestones match your wallet yet.</strong><span>PointPilot will add trackers as each India-30 rule set is source-verified.</span></div>}
  <div className="spendGuardrail"><span>ⓘ</span><p>Progress is based on totals you enter, not a bank statement connection. Issuer-posted eligible spend is authoritative. Confirm exclusions, reversals, taxes, cycle dates and benefit posting with the issuer before changing spending purely to reach a threshold.</p></div>
 </section>;
}
