"use client";
import {useState} from "react";
import {buildPersonalValue} from "../../lib/booking-decision.js";
const labels={cash:"Pay cash",direct:"Selected card redemption",award:"Airline award"};
const money=n=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:2}).format(n);
export default function PersonalValue({decision,direct,award}){
 const [values,setValues]=useState({});
 const model=buildPersonalValue({decision,direct,award,values});
 if(!model||model.rows.length<2)return null;
 return <details className="personalValue"><summary>Is using points actually better value?</summary><p>Enter the value you would give up by spending each kind of point. These are your assumptions, not PointPilot valuations. Leave an unknown value blank; enter zero only if you intentionally value it at zero.</p><div className="valueInputs">{model.requirements.map(item=><label key={item.key}>{item.label}<input type="number" min="0" step="0.01" inputMode="decimal" placeholder="Your value" value={values[item.key]??""} onChange={event=>setValues(previous=>({...previous,[item.key]:event.target.value}))}/></label>)}</div><p>Modeled cost = cash payable + value of points consumed. For an award, we count existing miles used plus the source card points transferred—not the newly transferred miles again.</p><div className="valueTable"><table><caption>Cash and points cost under your assumptions</caption><thead><tr><th scope="col">Option</th><th scope="col">Cash</th><th scope="col">Points value spent</th><th scope="col">Modeled cost</th></tr></thead><tbody>{model.rows.map(row=><tr key={row.kind}><th scope="row">{labels[row.kind]}</th><td>{money(row.cash)}</td><td>{row.pointsValue==null?"Value needed":money(row.pointsValue)}</td><td>{row.total==null?"—":money(row.total)}</td></tr>)}</tbody></table></div><p aria-live="polite">{model.complete?`${labels[model.best.kind]} has the lowest modeled cost under your assumptions: ${money(model.best.total)}. This is conditional on route eligibility and quote availability.`:"Add every required value to compare fairly. We do not rank partially valued options."}</p><p>Entered booking and transfer fees are included in cash. Unentered fees, foregone reward earnings, cancellation costs and voucher leftovers are excluded. Estimates do not confirm an award seat. Values stay only in this open comparison and are cleared when it is closed by leaving the page.</p><button type="button" onClick={()=>setValues({})}>Reset assumptions</button></details>;
}
