"use client";
import {useEffect,useMemo,useState} from "react";
import {getSupabase} from "../../lib/supabase-browser.js";
import {AIRLINE_PROGRAMS} from "../../lib/airline-programs.js";
import {buildAwardFunding,buildDirectRedemptions,transferRatioText} from "../../lib/reward-planner.js";

const DEFAULT_GOAL={goal_name:"My next award trip",origin:"BOM",destination:"LHR",travel_date:"",cabin:"BUSINESS",program_code:"air-india-maharaja",cash_fare:75000,taxes:8500,miles_required:45000};
const missingTable=error=>["42P01","PGRST205"].includes(error?.code);
const fmt=value=>Number(value||0).toLocaleString("en-IN");
const daysTo=value=>value?Math.ceil((new Date(`${value}T12:00:00`).getTime()-Date.now())/86400000):null;

export default function TripGoal({wallet,userId}){
 const[goal,setGoal]=useState(DEFAULT_GOAL),[saved,setSaved]=useState(false),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[rules,setRules]=useState([]),[balances,setBalances]=useState([]),[error,setError]=useState("");
 useEffect(()=>{let active=true;(async()=>{if(!userId)return;const sb=getSupabase();const[{data:g,error:goalError},{data:r,error:rulesError},{data:b,error:balanceError}]=await Promise.all([sb.from("user_trip_goals").select("*").eq("user_id",userId).maybeSingle(),sb.from("reward_rules").select("*").eq("active",true),sb.from("airline_mile_balances").select("*").eq("user_id",userId)]);if(rulesError)throw rulesError;if(balanceError&&!missingTable(balanceError))throw balanceError;if(goalError&&!missingTable(goalError))throw goalError;if(!active)return;setRules(r||[]);setBalances(b||[]);if(g){setGoal({...DEFAULT_GOAL,...g,travel_date:g.travel_date||""});setSaved(true)}else if(missingTable(goalError))setError("Trip Goals are being activated for this workspace.");setLoading(false)})().catch(err=>{if(active){setError(err?.message||"Unable to load your trip goal.");setLoading(false)}});return()=>{active=false}},[userId]);
 const award=useMemo(()=>buildAwardFunding({wallet,rules,balances,programCode:goal.program_code,milesRequired:goal.miles_required,cashFare:goal.cash_fare,taxes:goal.taxes}),[wallet,rules,balances,goal]);
 const direct=useMemo(()=>buildDirectRedemptions(wallet,rules,goal.cash_fare),[wallet,rules,goal.cash_fare]);
 const programme=AIRLINE_PROGRAMS.find(item=>item.code===goal.program_code)||AIRLINE_PROGRAMS[0];
 const remainingDays=daysTo(goal.travel_date);
 const update=(key,value)=>setGoal(previous=>({...previous,[key]:value}));
 const save=async event=>{event.preventDefault();setError("");setSaving(true);const payload={user_id:userId,goal_name:String(goal.goal_name||"").trim(),origin:String(goal.origin||"").toUpperCase(),destination:String(goal.destination||"").toUpperCase(),travel_date:goal.travel_date||null,cabin:goal.cabin,program_code:goal.program_code,cash_fare:Math.max(0,Number(goal.cash_fare)||0),taxes:Math.max(0,Number(goal.taxes)||0),miles_required:Math.max(0,Math.round(Number(goal.miles_required)||0)),updated_at:new Date().toISOString()};const{data,error:saveError}=await getSupabase().from("user_trip_goals").upsert(payload,{onConflict:"user_id"}).select().single();setSaving(false);if(saveError){setError(missingTable(saveError)?"Trip Goals need the pending database migration before they can be saved.":saveError.message);return}setGoal({...DEFAULT_GOAL,...data,travel_date:data.travel_date||""});setSaved(true)};
 const recommendation=award.shortfall===0?`Confirm a live ${programme.name} award before transferring any card points.`:award.routes.some(route=>route.contribution>0)?`Your verified card routes can close ${fmt(award.plannedTransfer)} of the gap; ${fmt(award.shortfall)} miles remain.`:direct[0]?`Use ${direct[0].card.card_name}'s ₹${fmt(direct[0].value)} verified direct value as the cash benchmark.`:"Add a matching balance or sourced transfer route before committing points.";
 return <section className="tripGoal" id="trip-goal"><div className="sectionHead tripGoalHead"><div><span className="sectionKicker">YOUR NEXT TRIP</span><h2>Give every point a destination.</h2><p>Save one travel target and return to a live funding gap built only from your wallet, your miles and verified routes.</p></div><span className="goalStatus">{saved?"SAVED TO YOUR ACCOUNT":"PRIVATE DRAFT"}</span></div>
 <div className="goalShell"><form className="goalForm" onSubmit={save}><div className="goalFormTop"><div><small>01 / TRIP BRIEF</small><h3>{saved?goal.goal_name:"Build your target"}</h3></div><span>{loading?"Loading…":remainingDays==null?"Choose a date":remainingDays<0?"Date passed":`${remainingDays} days away`}</span></div><div className="goalInputs"><label className="goalName">Goal name<input required maxLength="80" value={goal.goal_name} onChange={e=>update("goal_name",e.target.value)}/></label><label>From<input required maxLength="3" pattern="[A-Za-z]{3}" value={goal.origin} onChange={e=>update("origin",e.target.value.toUpperCase())}/></label><label>To<input required maxLength="3" pattern="[A-Za-z]{3}" value={goal.destination} onChange={e=>update("destination",e.target.value.toUpperCase())}/></label><label>Travel date<input type="date" value={goal.travel_date} onChange={e=>update("travel_date",e.target.value)}/></label><label>Cabin<select value={goal.cabin} onChange={e=>update("cabin",e.target.value)}><option value="ECONOMY">Economy</option><option value="PREMIUM_ECONOMY">Premium Economy</option><option value="BUSINESS">Business</option><option value="FIRST">First</option></select></label><label className="goalProgramme">Award programme<select value={goal.program_code} onChange={e=>update("program_code",e.target.value)}>{AIRLINE_PROGRAMS.map(item=><option value={item.code} key={item.code}>{item.airline} · {item.name}</option>)}</select></label><label>Cash fare (₹)<input type="number" min="0" value={goal.cash_fare} onChange={e=>update("cash_fare",e.target.value)}/></label><label>Taxes (₹)<input type="number" min="0" value={goal.taxes} onChange={e=>update("taxes",e.target.value)}/></label><label>Miles required<input type="number" min="0" value={goal.miles_required} onChange={e=>update("miles_required",e.target.value)}/></label></div>{error&&<div className="goalError">{error}</div>}<div className="goalSave"><button disabled={saving||loading}>{saving?"Saving…":saved?"Update trip goal":"Save trip goal"}</button><span>Stored privately under this signed-in account</span></div></form>
 <aside className="goalProgress"><div className="goalRoute"><small>{goal.cabin.replace("_"," ")} · {programme.initials}</small><strong>{goal.origin||"—"}<i>→</i>{goal.destination||"—"}</strong><span>{goal.travel_date?new Date(`${goal.travel_date}T12:00:00`).toLocaleDateString("en-IN",{day:"numeric",month:"short",year:"numeric"}):"Date flexible"}</span></div><div className="goalCoverage"><div className="goalRing" style={{"--goal":`${Math.round(award.coverage*100)}%`}}><strong>{Math.round(award.coverage*100)}%</strong><small>funded</small></div><dl><div><dt>Miles held</dt><dd>{fmt(award.existing)}</dd></div><div><dt>Verified transfers</dt><dd>{fmt(award.plannedTransfer)}</dd></div><div><dt>Funding gap</dt><dd className={award.shortfall?"goalGap":"goalDone"}>{fmt(award.shortfall)}</dd></div><div><dt>Net value</dt><dd>₹{award.valuePerMile.toFixed(2)}/mile</dd></div></dl></div><div className="goalNext"><small>NEXT BEST ACTION</small><b>{recommendation}</b></div><a href={programme.award_search_url} target="_blank" rel="noreferrer">Check live award space with {programme.airline} <span>↗</span></a></aside></div>
 {award.routes.some(route=>route.transferable>0)&&<div className="goalTransferStrip"><span>VERIFIED FUNDING ROUTE</span>{award.routes.filter(route=>route.transferable>0).slice(0,3).map((route,index)=><div key={route.rule.id||index}><b>{route.card.card_name}</b><small>{transferRatioText(route.ratio)} · {fmt(route.contribution)} planned miles</small></div>)}<p>Confirm the exact award seat and taxes first. Card-to-airline transfers can be irreversible.</p></div>}</section>;
}
